### ISSUE TITLE
Since "updated to work with blogofile 0.8.1" commit I cannot build the page.

### ISSUE THREAD

**Issue by punkto** [openframeworks/ofSite#150]
I have tried to build the latest ofSite using the already available instructions placed in readme.md (AKA using Blogofile 0.7.1) and it doesn't work. I have been testing and I have found that I cannot compile since commit  [543223439fa4](https://github.com/openframeworks/ofSite/commit/543223439fa48a3b91aeea77f1e59a611a067597).

I have tried with Blogofile 0.8b1 (installed by "pip install -U Blogofile" + "pip install -U blogofile_blog" in my Debian testing machine) with no success.

Which Blogofile version are you using, people? Should readme.md be updated with instructions for the new version? Am I doing something wrong (my apologies in advance)?

Here are my outputs when I try to compile:

With 0.7.1

```
Traceback (most recent call last):
  File "/usr/local/bin/blogofile", line 9, in <module>
    load_entry_point('Blogofile==1.0.0-DEV', 'console_scripts', 'blogofile')()
  File "/usr/local/lib/python2.7/dist-packages/Blogofile-1.0.0_DEV-py2.7.egg/blogofile/main.py", line 135, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/Blogofile-1.0.0_DEV-py2.7.egg/blogofile/main.py", line 201, in do_build
    writer.write_site()
  File "/usr/local/lib/python2.7/dist-packages/Blogofile-1.0.0_DEV-py2.7.egg/blogofile/writer.py", line 52, in write_site
    self.__run_controllers()
  File "/usr/local/lib/python2.7/dist-packages/Blogofile-1.0.0_DEV-py2.7.egg/blogofile/writer.py", line 136, in __run_controllers
    controller.run_all()
  File "/usr/local/lib/python2.7/dist-packages/Blogofile-1.0.0_DEV-py2.7.egg/blogofile/controller.py", line 203, in run_all
    controller.run()
  File "_controllers/tutorials.py", line 98, in run
    bf.template.materialize_template("tutorials.mako", ('tutorials',"index.html"), {'categories':categories} )
TypeError: __call__() takes exactly 1 argument (4 given)
```

With 0.8.1

```
WARNING:blogofile.template:Location is used more than once: _site/documentation/types/ofBaseImage.html
WARNING:blogofile.template:Location is used more than once: _site/documentation/serial/ofSerialDeviceInfo.html
WARNING:blogofile.template:Location is used more than once: _site/documentation/utils/ofPtr.html
WARNING:blogofile.template:Location is used more than once: _site/documentation/types/ofBaseHasPixels.html
ERROR:blogofile.template:Error rendering template: gallery/index.html.mako


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Blogofile-0.8b1-py2.7.egg/blogofile/template.py", line 154, in render
    rendered = self.mako_template.render(**self)
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 814, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 760, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "gallery/index.html.mako", line 1, in _mako_inherit
    <%inherit file="base.mako" />
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 719, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 751, in _lookup_template
    raise exceptions.TemplateLookupException(str(compat.exception_as()))
TemplateLookupException: Cant locate template for uri u'gallery/base.mako'

ERROR:blogofile:Fatal build error occured, calling bf.config.build_exception()
Traceback (most recent call last):
  File "/usr/local/bin/blogofile", line 9, in <module>
    load_entry_point('Blogofile==0.8b1', 'console_scripts', 'blogofile')()
  File "/usr/local/lib/python2.7/dist-packages/Blogofile-0.8b1-py2.7.egg/blogofile/main.py", line 58, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/Blogofile-0.8b1-py2.7.egg/blogofile/main.py", line 388, in do_build
    writer.write_site()
  File "/usr/local/lib/python2.7/dist-packages/Blogofile-0.8b1-py2.7.egg/blogofile/writer.py", line 50, in write_site
    self.__write_files()
  File "/usr/local/lib/python2.7/dist-packages/Blogofile-0.8b1-py2.7.egg/blogofile/writer.py", line 127, in __write_files
    util.path_join(root, html_path))
  File "/usr/local/lib/python2.7/dist-packages/Blogofile-0.8b1-py2.7.egg/blogofile/template.py", line 386, in materialize_template
    template.render(location)
  File "/usr/local/lib/python2.7/dist-packages/Blogofile-0.8b1-py2.7.egg/blogofile/template.py", line 154, in render
    rendered = self.mako_template.render(**self)
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 814, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 760, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "gallery_index_html_mako", line 24, in _mako_inherit
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 719, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 751, in _lookup_template
    raise exceptions.TemplateLookupException(str(compat.exception_as()))
mako.exceptions.TemplateLookupException: Cant locate template for uri u'gallery/base.mako'
```

**Comment by edap** [comment]
I was having the same error using blogofile installed with brew (0.8.3). I've downloaded it from source like @punkto said, run `python setup.py install` and it works. Also, i've to set some environment variables
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
