### ISSUE TITLE
build.sh broken since 23e87cd

### ISSUE THREAD

**Issue by stroborobo** [openframeworks/ofSite#428]
```
bo-mbp:bo [~/src/ofSite]I> ./build.sh
[2016-01-29T18:31:28Z] ERROR: yapsy: Unable to import plugin: /Users/bo/src/ofSite/plugins/documentation/documentation
Traceback (most recent call last):
  File "/Users/bo/src/ofSite/nikola/lib/python3.5/site-packages/yapsy/PluginManager.py", line 485, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/Users/bo/src/ofSite/nikola/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/Users/bo/src/ofSite/nikola/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/bo/src/ofSite/plugins/documentation/documentation/__init__.py", line 17, in <module>
    import html2text
ImportError: No module named 'html2text'
Scanning posts.............done!
^C
[...]
```

**Comment by arturoc** [comment]
this is fixed already but you'll need beautiful soup now, you can just run install.sh again and it'll install it for you

**Comment by stroborobo** [comment]
Thanks!
