### ISSUE TITLE
Nikola crash when building site

### ISSUE THREAD

**Issue by mikechambers** [openframeworks/ofSite#535]
Trying to compile site on Mac OSX. A bit chunk of the site will compile, but then crashes when trying to build docs.

Mac OSX 10.11.4
Python 3.5.1

```
.  tutorials:output/learning/index.html
.  documentation:documentation
########################################
TaskError - taskid:documentation:documentation
PythonAction Error
Traceback (most recent call last):
  File "/Users/mesh/src/ofSite/nikola/lib/python3.5/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/mesh/src/ofSite/plugins/documentation/documentation/__init__.py", line 448, in create_docs
    self.site.render_template(template_name, tdst, context)
  File "/Users/mesh/src/ofSite/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 1165, in render_template
    template_name, None, local_context)
  File "/Users/mesh/src/ofSite/nikola/lib/python3.5/site-packages/nikola/plugins/template/mako.py", line 108, in render_template
    data = template.render_unicode(**context)
  File "/Users/mesh/src/ofSite/nikola/lib/python3.5/site-packages/mako/template.py", line 454, in render_unicode
    as_unicode=True)
  File "/Users/mesh/src/ofSite/nikola/lib/python3.5/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/mesh/src/ofSite/nikola/lib/python3.5/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/mesh/src/ofSite/nikola/lib/python3.5/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/Users/mesh/src/ofSite/cache/.mako.tmp/base.tmpl.py", line 253, in render_body
    context['self'].content(**pageargs)
  File "/Users/mesh/src/ofSite/cache/.mako.tmp/documentation.mako.py", line 92, in render_content
    runtime._include_file(context, 'documentation_index_block.mako', _template_uri, module=module, classes=classes, show_header=True, subtitle=module_subtitles[module])
KeyError: ''
```

Issue in current docs? Configuration issue on myside?

Is there a way to just build the site, without documentation?

**Comment by mikechambers** [comment]
Looking into this a bit more. It looks like there is some issue with one of the markdown files in documentation, although I havent been able to track down the exact file.

If I remove all of the files in the documentation folder, except for index.md, the nikola will make enough progress so it creates the page im working on (although it ends up throwing another error eventually).

**Comment by arturoc** [comment]
you can disable the docs in conf.py, line 1206:

```
# Plugins you don't want to use. Be careful :-)
# DISABLED_PLUGINS = ["documentation"]
```

just uncomment that line, you can also disable the tutorials by adding `,"tutorials"` after documentation

**Comment by mikechambers** [comment]
Thanks. Do you know if there is a way to get it to spit out which markdown file is is choking on? I wouldn't mind spending some time trying to track down, and fix the issues.

```
Scanning posts..............done!
2016-04-27 07:55 python3.5[6634] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/mesh/src/ofSite/nikola/lib/python3.5/site-packages/fsevents.py", line 126, in run
    self._schedule(stream)
  File "/Users/mesh/src/ofSite/nikola/lib/python3.5/site-packages/fsevents.py", line 150, in _schedule
    schedule(self, stream, callback, stream.paths, stream.since, stream.latency, stream.cflags)
SystemError: <built-in function schedule> returned NULL without setting an error

```

**Comment by arturoc** [comment]
it usually says so if it's something related with the parsing of the docs. it seems like some internal bug that might only be happening when parsing the docs but not really in the docs code. perhaps try reporting the error in the nikola github: https://github.com/getnikola/nikola

**Comment by arturoc** [comment]
closing this since it seems to build fine now
