### ISSUE TITLE
cannot install build tools (macOS14)

### ISSUE THREAD

**Issue by artificiel** [openframeworks/ofSite#813]
following the instruction, I had to specifiy pip3 (instead of plain pip) and got a lot of action going with `install.sh`...
but it chokes here:

```python
Collecting markdown==2.6.5
  Downloading Markdown-2.6.5.zip (412 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 412.0/412.0 kB 16.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: markdown
  Building wheel for markdown (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      /private/var/folders/yd/9qhlg5md2kjd0z_f4rz4vwyh0000gn/T/pip-install-qudeu96r/markdown_69de6074df2b456e81bb63d73ec8f5b4/setup.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
        import imp
      Converting docs/release-2.3.txt -> build/docs/release-2.3.html
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/yd/9qhlg5md2kjd0z_f4rz4vwyh0000gn/T/pip-install-qudeu96r/markdown_69de6074df2b456e81bb63d73ec8f5b4/setup.py", line 234, in <module>
          setup(
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/setuptools/dist.py", line 1001, in run_command
          super().run_command(command)
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/setuptools/dist.py", line 1001, in run_command
          super().run_command(command)
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/setuptools/dist.py", line 1001, in run_command
          super().run_command(command)
        File "/Users/brtn/source_control/ofSite/nikola/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/yd/9qhlg5md2kjd0z_f4rz4vwyh0000gn/T/pip-install-qudeu96r/markdown_69de6074df2b456e81bb63d73ec8f5b4/setup.py", line 184, in run
          out = template % self._get_context(src, outfile)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yd/9qhlg5md2kjd0z_f4rz4vwyh0000gn/T/pip-install-qudeu96r/markdown_69de6074df2b456e81bb63d73ec8f5b4/setup.py", line 116, in _get_context
          c['body'] = self.md.convert(src)
                      ^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yd/9qhlg5md2kjd0z_f4rz4vwyh0000gn/T/pip-install-qudeu96r/markdown_69de6074df2b456e81bb63d73ec8f5b4/build/lib/markdown/__init__.py", line 375, in convert
          newRoot = treeprocessor.run(root)
                    ^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yd/9qhlg5md2kjd0z_f4rz4vwyh0000gn/T/pip-install-qudeu96r/markdown_69de6074df2b456e81bb63d73ec8f5b4/build/lib/markdown/treeprocessors.py", line 361, in run
          brs = root.getiterator('br')
                ^^^^^^^^^^^^^^^^
      AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for markdown
  Running setup.py clean for markdown
Failed to build markdown
ERROR: Could not build wheels for markdown, which is required to install pyproject.toml-based projects

 ^ Received error installing website static generator ^
```

**Comment by smeyfroi** [comment]
This PR might be interesting. I opened it Draft until someone else had a chance to test it, although it was quite a while ago now. Interested if it helps you: https://github.com/openframeworks/ofSite/pull/795
